### ISSUE TITLE
The version installed on macos constantly displays the connection and cannot exit. Even after re-downloading, the connection status is still displayed.

### ISSUE THREAD

**Issue by cuichaobaobao** [music-assistant/companion#54]
I installed The desktop companion app for Music Assistant on mac mini m2. You can enter it when configuring it for the first time. After entering, you want to select the output device as a headphone speaker. After selection, it will not take effect. Then the program crashed. After I uninstalled it, it kept spinning and connecting when I installed it. This was the case no matter how I uninstalled and reinstalled. Please help check.

<img width="1361" alt="截屏2024-11-27 09 22 46" src="https://github.com/user-attachments/assets/43b810ea-8f1d-4d64-ae3a-cc3fb9b39659">

**Comment by arctixdev** [comment]
Hi sorry, I don't know what is causing this. The project isn't being actively maintained at the moment, because I am the only contributor but I am off the project for the next half a year or so

**Comment by RutgerJoosten** [comment]
For when ther is time or another contributer. I have the same on windows 11.

**Comment by CurlyBen** [comment]
I've encountered the same issue when entering the wrong server details - there doesn't appear to be any way to edit them after pressing connect, even after reinstalling

**Comment by arctixdev** [comment]
It should show the setup screen when the connection fails, but honestly a lot of stuff isnt working atm sadly. Possibly if you turn off wifi/ethernet and then try to open it it might show it again. Otherwise you can right click, inspect element, under storage just delete all the entries for tauri.localhost (I am not 100% sure this is what its called on windows)

**Comment by RutgerJoosten** [comment]
I got back in the app! 
It was indeed bad server details. When you inspect and go to application > Local Storage > http://tauri.localhost
Here you can edit the settings
The key "mass_ip" should not have the port included and for me the "mass_port" had the standard Home Assistant ip (8123). This should be '8095'

![Image](https://github.com/user-attachments/assets/9dd219e8-1a35-4b84-8f84-0727996149da)

After this click right mouse on the Music Assistant tray icon and select Relaunch.
I cant get the music playin on "This Device" sadly, but I can stream to my Google Nest speakers :)

( I do get a certain error a lot. doesnt really matter what I click, I get this error in the inspector console:

index-ba1bcf8c.js:13 
 TypeError: Cannot read properties of undefined (reading 'length')
    at Default-b08e3af5.js:1:51415
    at Object.t [as append] (index-ba1bcf8c.js:13:2224)
    at default (index-ba1bcf8c.js:43:121417)
    at index-ba1bcf8c.js:13:21231
    at Object.t [as default] (index-ba1bcf8c.js:13:2224)
    at Proxy.<anonymous> (index-ba1bcf8c.js:43:49852)
    at Ki (index-ba1bcf8c.js:13:35180)
    at Hd.O [as fn] (index-ba1bcf8c.js:13:26348)
    at Hd.run (index-ba1bcf8c.js:9:1741)
    at U (index-ba1bcf8c.js:13:25985)
)
